services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-sqlite-alpine
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: php artisan serve --host=0.0.0.0 --port=9000

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-sqlite-alpine
    container_name: laravel_artisan
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    entrypoint: ["php", "artisan"]

  # Uncomment if you need Redis in your project
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
