services:
  app:
    build:
      context: ../../  # Build context points to the project root
      dockerfile: docker/production/Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:CMttCpC8BVZ0VRlN6se/MB0J1Eftk18CIpGY9eFoICU=
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ../../public:/var/www/html/public  # Serve only the public directory
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"  # Expose port 80 for HTTP
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
